version: '3.8'
services:
  mysql:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: imdb_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "3306:3306"
    networks:
      - backend

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
